<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.resolver.value.unique_values_pool' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Resolver/UniqueValuesPool.php';

return $this->services['nelmio_alice.generator.resolver.value.unique_values_pool'] = new \Nelmio\Alice\Generator\Resolver\UniqueValuesPool();
