<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.fixture_builder.denormalizer.fixture.simple_fixture_bag_denormalizer' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/FixtureBagDenormalizerInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Fixture/SimpleFixtureBagDenormalizer.php';

return $this->services['nelmio_alice.fixture_builder.denormalizer.fixture.simple_fixture_bag_denormalizer'] = new \Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\SimpleFixtureBagDenormalizer(${($_ = isset($this->services['nelmio_alice.fixture_builder.denormalizer.fixture.registry_denormalizer']) ? $this->services['nelmio_alice.fixture_builder.denormalizer.fixture.registry_denormalizer'] : $this->load('getNelmioAlice_FixtureBuilder_Denormalizer_Fixture_RegistryDenormalizerService.php')) && false ?: '_'}, ${($_ = isset($this->services['nelmio_alice.fixture_builder.denormalizer.flag_parser.element']) ? $this->services['nelmio_alice.fixture_builder.denormalizer.flag_parser.element'] : $this->load('getNelmioAlice_FixtureBuilder_Denormalizer_FlagParser_ElementService.php')) && false ?: '_'});
