<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.fixture_builder.denormalizer.simple' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/FixtureBuilder/DenormalizerInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/SimpleDenormalizer.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/ParameterBagDenormalizerInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Parameter/SimpleParameterBagDenormalizer.php';

return $this->services['nelmio_alice.fixture_builder.denormalizer.simple'] = new \Nelmio\Alice\FixtureBuilder\Denormalizer\SimpleDenormalizer(${($_ = isset($this->services['nelmio_alice.fixture_builder.denormalizer.parameter.simple_parameter_bag_denormalizer']) ? $this->services['nelmio_alice.fixture_builder.denormalizer.parameter.simple_parameter_bag_denormalizer'] : $this->services['nelmio_alice.fixture_builder.denormalizer.parameter.simple_parameter_bag_denormalizer'] = new \Nelmio\Alice\FixtureBuilder\Denormalizer\Parameter\SimpleParameterBagDenormalizer()) && false ?: '_'}, ${($_ = isset($this->services['nelmio_alice.fixture_builder.denormalizer.fixture.simple_fixture_bag_denormalizer']) ? $this->services['nelmio_alice.fixture_builder.denormalizer.fixture.simple_fixture_bag_denormalizer'] : $this->load('getNelmioAlice_FixtureBuilder_Denormalizer_Fixture_SimpleFixtureBagDenormalizerService.php')) && false ?: '_'});
