<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.double_pass' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/GeneratorInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/DoublePassGenerator.php';

return $this->services['nelmio_alice.generator.double_pass'] = new \Nelmio\Alice\Generator\DoublePassGenerator(${($_ = isset($this->services['nelmio_alice.generator.resolver.fixture_set.remove_conflicting_objects']) ? $this->services['nelmio_alice.generator.resolver.fixture_set.remove_conflicting_objects'] : $this->load('getNelmioAlice_Generator_Resolver_FixtureSet_RemoveConflictingObjectsService.php')) && false ?: '_'}, ${($_ = isset($this->services['nelmio_alice.generator.object_generator.complete']) ? $this->services['nelmio_alice.generator.object_generator.complete'] : $this->load('getNelmioAlice_Generator_ObjectGenerator_CompleteService.php')) && false ?: '_'});
