<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.resolver.parameter_bag.simple' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Resolver/ParameterBagResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Resolver/Parameter/SimpleParameterBagResolver.php';

return $this->services['nelmio_alice.generator.resolver.parameter_bag.simple'] = new \Nelmio\Alice\Generator\Resolver\Parameter\SimpleParameterBagResolver(${($_ = isset($this->services['nelmio_alice.generator.resolver.parameter.registry']) ? $this->services['nelmio_alice.generator.resolver.parameter.registry'] : $this->load('getNelmioAlice_Generator_Resolver_Parameter_RegistryService.php')) && false ?: '_'});
