<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.file_parser.runtime_cache' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/ParserInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Parser/RuntimeCacheParser.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/FileLocatorInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/FileLocator/DefaultFileLocator.php';

return $this->services['nelmio_alice.file_parser.runtime_cache'] = new \Nelmio\Alice\Parser\RuntimeCacheParser(${($_ = isset($this->services['nelmio_alice.file_parser.registry']) ? $this->services['nelmio_alice.file_parser.registry'] : $this->load('getNelmioAlice_FileParser_RegistryService.php')) && false ?: '_'}, ${($_ = isset($this->services['nelmio_alice.file_locator.default']) ? $this->services['nelmio_alice.file_locator.default'] : $this->services['nelmio_alice.file_locator.default'] = new \Nelmio\Alice\FileLocator\DefaultFileLocator()) && false ?: '_'}, ${($_ = isset($this->services['nelmio_alice.file_parser.default_include_processor']) ? $this->services['nelmio_alice.file_parser.default_include_processor'] : $this->load('getNelmioAlice_FileParser_DefaultIncludeProcessorService.php')) && false ?: '_'});
