<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.object_generator.simple' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/ObjectGeneratorInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/ObjectGenerator/SimpleObjectGenerator.php';

return $this->services['nelmio_alice.generator.object_generator.simple'] = new \Nelmio\Alice\Generator\ObjectGenerator\SimpleObjectGenerator(${($_ = isset($this->services['nelmio_alice.generator.resolver.value.registry']) ? $this->services['nelmio_alice.generator.resolver.value.registry'] : $this->load('getNelmioAlice_Generator_Resolver_Value_RegistryService.php')) && false ?: '_'}, ${($_ = isset($this->services['nelmio_alice.generator.instantiator.existing_instance']) ? $this->services['nelmio_alice.generator.instantiator.existing_instance'] : $this->load('getNelmioAlice_Generator_Instantiator_ExistingInstanceService.php')) && false ?: '_'}, ${($_ = isset($this->services['nelmio_alice.generator.hydrator.simple']) ? $this->services['nelmio_alice.generator.hydrator.simple'] : $this->load('getNelmioAlice_Generator_Hydrator_SimpleService.php')) && false ?: '_'}, ${($_ = isset($this->services['nelmio_alice.generator.caller.simple']) ? $this->services['nelmio_alice.generator.caller.simple'] : $this->load('getNelmioAlice_Generator_Caller_SimpleService.php')) && false ?: '_'});
