<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.instantiator.chainable.no_caller_method_instantiator' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/InstantiatorInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Instantiator/ChainableInstantiatorInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Instantiator/Chainable/AbstractChainableInstantiator.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Instantiator/Chainable/NoCallerMethodCallInstantiator.php';

return $this->services['nelmio_alice.generator.instantiator.chainable.no_caller_method_instantiator'] = new \Nelmio\Alice\Generator\Instantiator\Chainable\NoCallerMethodCallInstantiator();
