<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.fixture_builder.expression_language.parser.function_fixture_reference_parser' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/FixtureBuilder/ExpressionLanguage/ParserInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/FixtureBuilder/ExpressionLanguage/Parser/FunctionFixtureReferenceParser.php';

return $this->services['nelmio_alice.fixture_builder.expression_language.parser.function_fixture_reference_parser'] = new \Nelmio\Alice\FixtureBuilder\ExpressionLanguage\Parser\FunctionFixtureReferenceParser(${($_ = isset($this->services['nelmio_alice.fixture_builder.expression_language.parser.string_parser']) ? $this->services['nelmio_alice.fixture_builder.expression_language.parser.string_parser'] : $this->load('getNelmioAlice_FixtureBuilder_ExpressionLanguage_Parser_StringParserService.php')) && false ?: '_'});
