<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.file_parser.default_include_processor' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Parser/IncludeProcessorInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Parser/IncludeProcessor/DefaultIncludeProcessor.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/FileLocatorInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/FileLocator/DefaultFileLocator.php';

return $this->services['nelmio_alice.file_parser.default_include_processor'] = new \Nelmio\Alice\Parser\IncludeProcessor\DefaultIncludeProcessor(${($_ = isset($this->services['nelmio_alice.file_locator.default']) ? $this->services['nelmio_alice.file_locator.default'] : $this->services['nelmio_alice.file_locator.default'] = new \Nelmio\Alice\FileLocator\DefaultFileLocator()) && false ?: '_'});
