<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.resolver.fixture_set.simple' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/FixtureSetResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Resolver/FixtureSet/SimpleFixtureSetResolver.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Resolver/FixtureBagResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Resolver/Fixture/TemplateFixtureBagResolver.php';

return $this->services['nelmio_alice.generator.resolver.fixture_set.simple'] = new \Nelmio\Alice\Generator\Resolver\FixtureSet\SimpleFixtureSetResolver(${($_ = isset($this->services['nelmio_alice.generator.resolver.parameter_bag.remove_conflicting_parameters']) ? $this->services['nelmio_alice.generator.resolver.parameter_bag.remove_conflicting_parameters'] : $this->load('getNelmioAlice_Generator_Resolver_ParameterBag_RemoveConflictingParametersService.php')) && false ?: '_'}, ${($_ = isset($this->services['nelmio_alice.generator.resolver.fixture_bag.template_bag']) ? $this->services['nelmio_alice.generator.resolver.fixture_bag.template_bag'] : $this->services['nelmio_alice.generator.resolver.fixture_bag.template_bag'] = new \Nelmio\Alice\Generator\Resolver\Fixture\TemplateFixtureBagResolver()) && false ?: '_'});
