<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.resolver.parameter_bag.remove_conflicting_parameters' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Resolver/ParameterBagResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Resolver/Parameter/RemoveConflictingParametersParameterBagResolver.php';

return $this->services['nelmio_alice.generator.resolver.parameter_bag.remove_conflicting_parameters'] = new \Nelmio\Alice\Generator\Resolver\Parameter\RemoveConflictingParametersParameterBagResolver(${($_ = isset($this->services['nelmio_alice.generator.resolver.parameter_bag.simple']) ? $this->services['nelmio_alice.generator.resolver.parameter_bag.simple'] : $this->load('getNelmioAlice_Generator_Resolver_ParameterBag_SimpleService.php')) && false ?: '_'});
