<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.resolver.fixture_set.remove_conflicting_objects' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/FixtureSetResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Resolver/FixtureSet/RemoveConflictingObjectsResolver.php';

return $this->services['nelmio_alice.generator.resolver.fixture_set.remove_conflicting_objects'] = new \Nelmio\Alice\Generator\Resolver\FixtureSet\RemoveConflictingObjectsResolver(${($_ = isset($this->services['nelmio_alice.generator.resolver.fixture_set.simple']) ? $this->services['nelmio_alice.generator.resolver.fixture_set.simple'] : $this->load('getNelmioAlice_Generator_Resolver_FixtureSet_SimpleService.php')) && false ?: '_'});
