<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.resolver.value.chainable.function_argument_resolver' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/ValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Resolver/Value/ChainableValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/ValueResolverAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Resolver/Value/Chainable/FunctionCallArgumentResolver.php';

return $this->services['nelmio_alice.generator.resolver.value.chainable.function_argument_resolver'] = new \Nelmio\Alice\Generator\Resolver\Value\Chainable\FunctionCallArgumentResolver(${($_ = isset($this->services['nelmio_alice.generator.resolver.value.chainable.php_value_resolver']) ? $this->services['nelmio_alice.generator.resolver.value.chainable.php_value_resolver'] : $this->load('getNelmioAlice_Generator_Resolver_Value_Chainable_PhpValueResolverService.php')) && false ?: '_'});
