<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.instantiator.existing_instance' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/InstantiatorInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/ValueResolverAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Instantiator/ExistingInstanceInstantiator.php';

return $this->services['nelmio_alice.generator.instantiator.existing_instance'] = new \Nelmio\Alice\Generator\Instantiator\ExistingInstanceInstantiator(${($_ = isset($this->services['nelmio_alice.generator.instantiator.resolver']) ? $this->services['nelmio_alice.generator.instantiator.resolver'] : $this->load('getNelmioAlice_Generator_Instantiator_ResolverService.php')) && false ?: '_'});
