<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.faker.provider.alice' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Faker/Provider/AliceProvider.php';

return $this->services['nelmio_alice.faker.provider.alice'] = new \Nelmio\Alice\Faker\Provider\AliceProvider();
