<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.caller.registry' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Caller/CallProcessorInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Caller/CallProcessorRegistry.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Caller/ChainableCallProcessorInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Caller/CallProcessorAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Caller/Chainable/ConfiguratorMethodCallProcessor.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Caller/Chainable/MethodCallWithReferenceProcessor.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Caller/Chainable/OptionalMethodCallProcessor.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Caller/Chainable/SimpleMethodCallProcessor.php';

return $this->services['nelmio_alice.generator.caller.registry'] = new \Nelmio\Alice\Generator\Caller\CallProcessorRegistry(array(0 => ${($_ = isset($this->services['nelmio_alice.generator.caller.chainable.configurator_method_call']) ? $this->services['nelmio_alice.generator.caller.chainable.configurator_method_call'] : $this->services['nelmio_alice.generator.caller.chainable.configurator_method_call'] = new \Nelmio\Alice\Generator\Caller\Chainable\ConfiguratorMethodCallProcessor()) && false ?: '_'}, 1 => ${($_ = isset($this->services['nelmio_alice.generator.caller.chainable.method_call_with_reference']) ? $this->services['nelmio_alice.generator.caller.chainable.method_call_with_reference'] : $this->services['nelmio_alice.generator.caller.chainable.method_call_with_reference'] = new \Nelmio\Alice\Generator\Caller\Chainable\MethodCallWithReferenceProcessor()) && false ?: '_'}, 2 => ${($_ = isset($this->services['nelmio_alice.generator.caller.chainable.optional_method_call']) ? $this->services['nelmio_alice.generator.caller.chainable.optional_method_call'] : $this->services['nelmio_alice.generator.caller.chainable.optional_method_call'] = new \Nelmio\Alice\Generator\Caller\Chainable\OptionalMethodCallProcessor()) && false ?: '_'}, 3 => ${($_ = isset($this->services['nelmio_alice.generator.caller.chainable.simple_call']) ? $this->services['nelmio_alice.generator.caller.chainable.simple_call'] : $this->services['nelmio_alice.generator.caller.chainable.simple_call'] = new \Nelmio\Alice\Generator\Caller\Chainable\SimpleMethodCallProcessor()) && false ?: '_'}));
