<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.faker.generator' shared service.

include_once $this->targetDirs[3].'/vendor/fzaninotto/faker/src/Faker/Factory.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Faker/Provider/AliceProvider.php';

$this->services['nelmio_alice.faker.generator'] = $instance = \Faker\Factory::create('en_US');

$instance->seed(1);
$instance->addProvider(${($_ = isset($this->services['nelmio_alice.faker.provider.alice']) ? $this->services['nelmio_alice.faker.provider.alice'] : $this->services['nelmio_alice.faker.provider.alice'] = new \Nelmio\Alice\Faker\Provider\AliceProvider()) && false ?: '_'});

return $instance;
