<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.fixture_builder.denormalizer.specs.simple' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Fixture/SpecificationsDenormalizerInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Fixture/SpecificationBagDenormalizer/SimpleSpecificationsDenormalizer.php';

return $this->services['nelmio_alice.fixture_builder.denormalizer.specs.simple'] = new \Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\SpecificationBagDenormalizer\SimpleSpecificationsDenormalizer(${($_ = isset($this->services['nelmio_alice.fixture_builder.denormalizer.fixture.specs.constructor.legacy_constructor_denormalizer']) ? $this->services['nelmio_alice.fixture_builder.denormalizer.fixture.specs.constructor.legacy_constructor_denormalizer'] : $this->load('getNelmioAlice_FixtureBuilder_Denormalizer_Fixture_Specs_Constructor_LegacyConstructorDenormalizerService.php')) && false ?: '_'}, ${($_ = isset($this->services['nelmio_alice.fixture_builder.denormalizer.fixture.specs.property.simple_denormalizer']) ? $this->services['nelmio_alice.fixture_builder.denormalizer.fixture.specs.property.simple_denormalizer'] : $this->load('getNelmioAlice_FixtureBuilder_Denormalizer_Fixture_Specs_Property_SimpleDenormalizerService.php')) && false ?: '_'}, ${($_ = isset($this->services['nelmio_alice.fixture_builder.denormalizer.fixture.specs.calls.simple_denormalizer']) ? $this->services['nelmio_alice.fixture_builder.denormalizer.fixture.specs.calls.simple_denormalizer'] : $this->load('getNelmioAlice_FixtureBuilder_Denormalizer_Fixture_Specs_Calls_SimpleDenormalizerService.php')) && false ?: '_'});
