<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.resolver.parameter.registry' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Resolver/ParameterResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Resolver/Parameter/ParameterResolverRegistry.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Resolver/ChainableParameterResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Resolver/Parameter/Chainable/StaticParameterResolver.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Resolver/ParameterResolverAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Resolver/Parameter/Chainable/ArrayParameterResolver.php';

return $this->services['nelmio_alice.generator.resolver.parameter.registry'] = new \Nelmio\Alice\Generator\Resolver\Parameter\ParameterResolverRegistry(array(0 => ${($_ = isset($this->services['nelmio_alice.generator.resolver.parameter.chainable.static_parameter_resolver']) ? $this->services['nelmio_alice.generator.resolver.parameter.chainable.static_parameter_resolver'] : $this->services['nelmio_alice.generator.resolver.parameter.chainable.static_parameter_resolver'] = new \Nelmio\Alice\Generator\Resolver\Parameter\Chainable\StaticParameterResolver()) && false ?: '_'}, 1 => ${($_ = isset($this->services['nelmio_alice.generator.resolver.parameter.chainable.array_parameter_resolver']) ? $this->services['nelmio_alice.generator.resolver.parameter.chainable.array_parameter_resolver'] : $this->services['nelmio_alice.generator.resolver.parameter.chainable.array_parameter_resolver'] = new \Nelmio\Alice\Generator\Resolver\Parameter\Chainable\ArrayParameterResolver()) && false ?: '_'}, 2 => ${($_ = isset($this->services['nelmio_alice.generator.resolver.parameter.chainable.recursive_parameter_resolver']) ? $this->services['nelmio_alice.generator.resolver.parameter.chainable.recursive_parameter_resolver'] : $this->load('getNelmioAlice_Generator_Resolver_Parameter_Chainable_RecursiveParameterResolverService.php')) && false ?: '_'}));
