<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.fixture_builder.denormalizer.fixture.specs.value.simple_value_denormalizer' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Fixture/SpecificationBagDenormalizer/ValueDenormalizerInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/FixtureBuilder/Denormalizer/Fixture/SpecificationBagDenormalizer/Value/SimpleValueDenormalizer.php';

return $this->services['nelmio_alice.fixture_builder.denormalizer.fixture.specs.value.simple_value_denormalizer'] = new \Nelmio\Alice\FixtureBuilder\Denormalizer\Fixture\SpecificationBagDenormalizer\Value\SimpleValueDenormalizer(${($_ = isset($this->services['nelmio_alice.fixture_builder.expression_language.parser.function_fixture_reference_parser']) ? $this->services['nelmio_alice.fixture_builder.expression_language.parser.function_fixture_reference_parser'] : $this->load('getNelmioAlice_FixtureBuilder_ExpressionLanguage_Parser_FunctionFixtureReferenceParserService.php')) && false ?: '_'});
