<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.caller.chainable.optional_method_call' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Caller/CallProcessorInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Caller/ChainableCallProcessorInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Caller/CallProcessorAwareInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Generator/Caller/Chainable/OptionalMethodCallProcessor.php';

return $this->services['nelmio_alice.generator.caller.chainable.optional_method_call'] = new \Nelmio\Alice\Generator\Caller\Chainable\OptionalMethodCallProcessor();
