<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.data_loader.simple' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/DataLoaderInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once $this->targetDirs[3].'/vendor/nelmio/alice/src/Loader/SimpleDataLoader.php';

return $this->services['nelmio_alice.data_loader.simple'] = new \Nelmio\Alice\Loader\SimpleDataLoader(${($_ = isset($this->services['nelmio_alice.fixture_builder.simple']) ? $this->services['nelmio_alice.fixture_builder.simple'] : $this->load('getNelmioAlice_FixtureBuilder_SimpleService.php')) && false ?: '_'}, ${($_ = isset($this->services['nelmio_alice.generator.double_pass']) ? $this->services['nelmio_alice.generator.double_pass'] : $this->load('getNelmioAlice_Generator_DoublePassService.php')) && false ?: '_'});
